language: haskell

install:
  - curl -o BuildFromSource.hs https://raw.githubusercontent.com/elm-lang/elm-platform/master/installers/BuildFromSource.hs
  - runhaskell BuildFromSource.hs 0.15
  - cd Elm-Platform/0.15
  - cp -r ../../assets .
  - cp -r ../../resources .
  - cp -r ../../src .
  - cp -r ../../Setup.hs .
  - cp -r ../../elm-package.json .
  - cp -r ../../elm-website.cabal .
  - cabal sandbox init --sandbox ..
  - cabal configure
  - cabal install --only-dependencies

script:
  - cd Elm-Platform/0.15
  - cabal build


